import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Trophy } from "lucide-react";
import { AppHeader } from "@/components/layout/AppHeader";
import { TopExclusiveCreators } from "@/components/goals/TopExclusiveCreators";
import { TeamAvatar } from "@/components/ui/team-avatar";
import { deals as fallbackDeals, isActiveDashboardDeal, type Deal } from "@/data/deals";
import { team as fallbackTeam } from "@/data/team";
import {
  leaderboardQuery,
  type LeaderboardFinancialMetrics,
  type LeaderboardMemberData,
} from "@/lib/sheets-public";
import { getCurrentDealMonthKey, normalizeDealMonthKey } from "@/lib/sheet-normalizer";

export const Route = createFileRoute("/leaderboard")({
  head: () => ({
    meta: [
      { title: "Leaderboard — Team Billion" },
      { name: "description", content: "Team financial performance and deal rankings." },
    ],
  }),
  component: LeaderboardPage,
});

const palette = [
  "var(--fun-lime)",
  "var(--fun-yellow)",
  "var(--fun-pink)",
  "var(--fun-purple)",
  "var(--fun-blue)",
  "var(--fun-orange)",
];

type Period = "monthly" | "longTerm";
type MetricKey = keyof LeaderboardFinancialMetrics;
type LeaderboardCategory = {
  key: MetricKey;
  label: string;
  shortLabel: string;
  description: (period: Period) => string;
  format: "money" | "count";
  longTermOnly?: boolean;
};

const categories: LeaderboardCategory[] = [
  {
    key: "commission",
    label: "Commission",
    shortLabel: "Commission",
    description: (period) =>
      period === "monthly"
        ? "Closed commission for the current month."
        : "Closed commission across all recorded deals.",
    format: "money",
  },
  {
    key: "dealsClosed",
    label: "Deals closed",
    shortLabel: "Deals",
    description: (period) =>
      period === "monthly"
        ? "Valid deals closed this month."
        : "Valid deals closed across all time.",
    format: "count",
  },
  {
    key: "dealValue",
    label: "Total deal value",
    shortLabel: "Deal value",
    description: (period) =>
      period === "monthly"
        ? "Total pricing from this month's valid deal rows."
        : "Total pricing across all valid deal rows.",
    format: "money",
  },
  {
    key: "profit",
    label: "Profit generated",
    shortLabel: "Profit",
    description: (period) =>
      period === "monthly"
        ? "Profit generated by this month's deals."
        : "Profit generated across all valid deals.",
    format: "money",
  },
  {
    key: "averageDealValue",
    label: "Average deal value",
    shortLabel: "Avg deal",
    description: (period) =>
      period === "monthly"
        ? "Average value of this month's valid deals."
        : "Average value across all valid deals.",
    format: "money",
  },
  {
    key: "exclusiveCreators",
    label: "Exclusive creators",
    shortLabel: "Exclusive",
    description: () => "Exclusive creators assigned to each member.",
    format: "count",
    longTermOnly: true,
  },
];

function formatCurrency(value: number) {
  return `£${Math.round(value).toLocaleString()}`;
}

function formatMetric(value: number, format: LeaderboardCategory["format"]) {
  return format === "money" ? formatCurrency(value) : value.toLocaleString();
}

function getDealProfit(deal: Pick<Deal, "totalPricingGbp" | "creatorTotalGbp">) {
  return Math.max(0, deal.totalPricingGbp - deal.creatorTotalGbp);
}

function PeriodSlider({
  period,
  onChange,
}: {
  period: Period;
  onChange: (period: Period) => void;
}) {
  return (
    <div
      className="mx-auto grid w-full max-w-lg grid-cols-2 rounded-[22px] border border-border bg-card p-1.5 shadow-sm ring-1 ring-border/60"
      role="tablist"
      aria-label="Leaderboard period"
    >
      {(["monthly", "longTerm"] as const).map((value) => (
        <button
          key={value}
          type="button"
          role="tab"
          aria-selected={period === value}
          onClick={() => onChange(value)}
          className={`rounded-[17px] px-5 py-3 text-sm font-black transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 ${
            period === value
              ? "bg-foreground text-background shadow-sm"
              : "text-muted-foreground hover:bg-muted hover:text-foreground"
          }`}
        >
          {value === "monthly" ? "Monthly" : "Long-term"}
        </button>
      ))}
    </div>
  );
}

function DealTable({
  title,
  description,
  deals,
  sortBy,
  showMember,
}: {
  title: string;
  description: string;
  deals: Deal[];
  sortBy: "pricing" | "profit";
  showMember: boolean;
}) {
  const rows = [...deals]
    .sort((a, b) =>
      sortBy === "pricing"
        ? b.totalPricingGbp - a.totalPricingGbp
        : getDealProfit(b) - getDealProfit(a),
    )
    .slice(0, 3);

  return (
    <section className="tb-hover-lift rounded-3xl bg-card p-6 ring-1 ring-border">
      <h3 className="text-base font-black">{title}</h3>
      <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      <div className="mt-4 overflow-x-auto rounded-2xl border border-border">
        <table className="w-full min-w-[760px] text-sm">
          <thead className="bg-muted/60 text-xs uppercase tracking-wide text-muted-foreground">
            <tr>
              <th className="px-4 py-3 text-left font-semibold">#</th>
              <th className="px-4 py-3 text-left font-semibold">Brand</th>
              <th className="px-4 py-3 text-left font-semibold">Creator</th>
              {showMember ? <th className="px-4 py-3 text-left font-semibold">Member</th> : null}
              <th className="px-4 py-3 text-right font-semibold">
                {sortBy === "pricing" ? "Total pricing" : "Profit"}
              </th>
              <th className="px-4 py-3 text-right font-semibold">Margin</th>
              <th className="px-4 py-3 text-right font-semibold">
                {sortBy === "pricing" ? "Profit" : "Total pricing"}
              </th>
              <th className="px-4 py-3 text-left font-semibold">Status</th>
            </tr>
          </thead>
          <tbody>
            {rows.length ? (
              rows.map((deal, index) => (
                <tr
                  key={deal.id}
                  className="tb-row-hover border-t border-border/60 hover:bg-muted/40"
                >
                  <td className="px-4 py-3 font-black">{index + 1}</td>
                  <td className="px-4 py-3 font-semibold">{deal.brand}</td>
                  <td className="px-4 py-3 text-muted-foreground">{deal.creator}</td>
                  {showMember ? <td className="px-4 py-3">{deal.manager}</td> : null}
                  <td className="px-4 py-3 text-right font-black">
                    {formatCurrency(
                      sortBy === "pricing" ? deal.totalPricingGbp : getDealProfit(deal),
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">{deal.profitMargin || "-"}</td>
                  <td className="px-4 py-3 text-right">
                    {formatCurrency(
                      sortBy === "pricing" ? getDealProfit(deal) : deal.totalPricingGbp,
                    )}
                  </td>
                  <td className="px-4 py-3">{deal.status}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan={showMember ? 8 : 7}
                  className="px-4 py-10 text-center text-muted-foreground"
                >
                  No matching deals for this view.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function LeaderboardPage() {
  const { data: leaderboardData } = useQuery(leaderboardQuery);
  const [period, setPeriod] = useState<Period>("monthly");
  const canUseLocalFallback =
    leaderboardData?.source === "fallback" || (!leaderboardData && import.meta.env.DEV);

  const fallbackLeaderboard: LeaderboardMemberData[] = fallbackTeam.map((member) => ({
    id: member.id,
    name: member.name,
    initials: member.initials,
    avatarUrl: member.avatarUrl,
    monthly: {
      commission: member.monthCommission,
      dealsClosed: member.dealsClosed,
      dealValue: member.revenue,
      profit: 0,
      averageDealValue: member.dealsClosed ? Math.round(member.revenue / member.dealsClosed) : 0,
      exclusiveCreators: 0,
    },
    longTerm: {
      commission: member.commission,
      dealsClosed: member.dealsClosed,
      dealValue: member.revenue,
      profit: 0,
      averageDealValue: member.dealsClosed ? Math.round(member.revenue / member.dealsClosed) : 0,
      exclusiveCreators: member.exclusiveCreators,
    },
  }));
  const members = leaderboardData?.members ?? (canUseLocalFallback ? fallbackLeaderboard : []);
  const metricsKey = period === "monthly" ? "monthly" : "longTerm";
  const commissionLeaders = [...members]
    .sort(
      (a, b) => b[metricsKey].commission - a[metricsKey].commission || a.name.localeCompare(b.name),
    )
    .slice(0, 3);
  const supportingCategories = categories.filter(
    (item) => item.key !== "commission" && !item.longTermOnly,
  );
  const rawDeals = leaderboardData?.deals ?? (canUseLocalFallback ? fallbackDeals : []);
  const periodDeals = rawDeals.filter(
    (deal) =>
      isActiveDashboardDeal(deal) &&
      (period === "longTerm" || normalizeDealMonthKey(deal.month) === getCurrentDealMonthKey()),
  );
  const scopedDeals = periodDeals;
  const scopedCreators = leaderboardData?.creators ?? [];
  const longTermDeals = rawDeals.filter(isActiveDashboardDeal);
  const periodLabel = period === "monthly" ? "this month" : "across all time";

  return (
    <div className="space-y-6">
      <AppHeader
        title="Leaderboard"
        subtitle="Compare financial performance, deal value, and creator results without outreach activity."
      />

      <PeriodSlider period={period} onChange={setPeriod} />

      <div className="flex flex-col gap-3 rounded-3xl bg-card p-4 ring-1 ring-border sm:flex-row sm:items-end sm:justify-between">
        <div>
          <div className="text-sm font-black">
            {period === "monthly" ? "Current month" : "Long-term performance"}
          </div>
          <p className="mt-1 text-xs text-muted-foreground">
            {period === "monthly"
              ? "Only deals recorded in the current month are included."
              : "All valid historical deal rows are included."}
          </p>
        </div>
      </div>

      <>
        <div>
          <h2 className="text-base font-black">Top 3 members by commission</h2>
          <p className="mt-1 text-xs text-muted-foreground">
            {period === "monthly"
              ? "Closed commission for the current month."
              : "Closed commission across all recorded deals."}
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          {commissionLeaders.map((member, index) => (
            <article
              key={member.id}
              className="tb-hover-lift tb-stat-tile overflow-hidden rounded-3xl p-6 ring-1 ring-border"
              style={{ background: palette[index] }}
            >
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide opacity-70">
                <Trophy className="h-3.5 w-3.5" /> #{index + 1}
              </div>
              <div className="mt-3 flex items-center gap-3">
                <TeamAvatar
                  name={member.name}
                  initials={member.initials}
                  avatarUrl={member.avatarUrl}
                  className="h-14 w-14"
                  fallbackClassName="bg-white/70 text-lg font-bold"
                />
                <div className="min-w-0">
                  <div className="truncate text-lg font-bold">{member.name}</div>
                  <div className="text-xs opacity-70">Team member</div>
                </div>
              </div>
              <div className="mt-4 text-3xl font-black">
                {formatCurrency(member[metricsKey].commission)}
              </div>
              <div className="text-xs opacity-70">
                Commission · {formatCurrency(member[metricsKey].averageDealValue)} avg deal
              </div>
            </article>
          ))}
        </div>

        <section className="rounded-3xl bg-card p-6 ring-1 ring-border">
          <div>
            <h2 className="text-base font-black">Other performance leaders</h2>
            <p className="mt-1 text-xs text-muted-foreground">
              Top three members for each supporting financial metric.
            </p>
          </div>
          <div className="mt-5 grid gap-x-8 gap-y-7 md:grid-cols-2 xl:grid-cols-4">
            {supportingCategories.map((item, metricIndex) => {
              const rankedMembers = [...members]
                .sort(
                  (a, b) =>
                    Number(b[metricsKey][item.key]) - Number(a[metricsKey][item.key]) ||
                    a.name.localeCompare(b.name),
                )
                .slice(0, 3);

              return (
                <div key={item.key}>
                  <div className="flex items-center gap-2">
                    <span
                      className="h-2.5 w-2.5 rounded-full"
                      style={{ background: palette[metricIndex + 1] }}
                    />
                    <h3 className="text-sm font-black">{item.label}</h3>
                  </div>

                  <div className="mt-3">
                    {rankedMembers.map((member, rank) => (
                      <div
                        key={member.id}
                        className="flex items-center gap-2 border-b border-border/60 py-3 last:border-b-0"
                      >
                        <span className="w-5 shrink-0 text-xs font-black text-muted-foreground/70">
                          #{rank + 1}
                        </span>
                        <div className="min-w-0 flex-1">
                          <div className="truncate text-sm font-semibold">{member.name}</div>
                        </div>
                        <div className="shrink-0 text-right text-sm font-black">
                          {formatMetric(Number(member[metricsKey][item.key]), item.format)}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </>

      {period === "longTerm" ? (
        <TopExclusiveCreators
          creators={scopedCreators}
          deals={longTermDeals}
          title="Top Exclusive Creators"
          description="Ranked by total deal value, with posted live deal value highlighted inside each bar."
        />
      ) : null}

      <DealTable
        title="Top 3 deals by total pricing"
        description={`Highest-value valid deal rows ${periodLabel}.`}
        deals={scopedDeals}
        sortBy="pricing"
        showMember
      />
      <DealTable
        title="Top 3 deals by profit"
        description={`Highest-profit valid deal rows ${periodLabel}. Profit is total pricing minus creator total.`}
        deals={scopedDeals}
        sortBy="profit"
        showMember
      />
    </div>
  );
}
