/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as BrandFinderRouteImport } from './routes/brand-finder'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ActiveBrandsRouteImport } from './routes/active-brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSlackFollowupsRouteImport } from './routes/api/slack-followups'
import { Route as ApiSlackDebugRouteImport } from './routes/api/slack-debug'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandFinderRoute = BrandFinderRouteImport.update({
  id: '/brand-finder',
  path: '/brand-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveBrandsRoute = ActiveBrandsRouteImport.update({
  id: '/active-brands',
  path: '/active-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlackFollowupsRoute = ApiSlackFollowupsRouteImport.update({
  id: '/api/slack-followups',
  path: '/api/slack-followups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlackDebugRoute = ApiSlackDebugRouteImport.update({
  id: '/api/slack-debug',
  path: '/api/slack-debug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-brands': typeof ActiveBrandsRoute
  '/assets': typeof AssetsRoute
  '/brand-finder': typeof BrandFinderRoute
  '/creators': typeof CreatorsRoute
  '/deals': typeof DealsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/goals': typeof GoalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/slack-debug': typeof ApiSlackDebugRoute
  '/api/slack-followups': typeof ApiSlackFollowupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-brands': typeof ActiveBrandsRoute
  '/assets': typeof AssetsRoute
  '/brand-finder': typeof BrandFinderRoute
  '/creators': typeof CreatorsRoute
  '/deals': typeof DealsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/goals': typeof GoalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/slack-debug': typeof ApiSlackDebugRoute
  '/api/slack-followups': typeof ApiSlackFollowupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-brands': typeof ActiveBrandsRoute
  '/assets': typeof AssetsRoute
  '/brand-finder': typeof BrandFinderRoute
  '/creators': typeof CreatorsRoute
  '/deals': typeof DealsRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/goals': typeof GoalsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/slack-debug': typeof ApiSlackDebugRoute
  '/api/slack-followups': typeof ApiSlackFollowupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-brands'
    | '/assets'
    | '/brand-finder'
    | '/creators'
    | '/deals'
    | '/diagnostics'
    | '/goals'
    | '/leaderboard'
    | '/api/slack-debug'
    | '/api/slack-followups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-brands'
    | '/assets'
    | '/brand-finder'
    | '/creators'
    | '/deals'
    | '/diagnostics'
    | '/goals'
    | '/leaderboard'
    | '/api/slack-debug'
    | '/api/slack-followups'
  id:
    | '__root__'
    | '/'
    | '/active-brands'
    | '/assets'
    | '/brand-finder'
    | '/creators'
    | '/deals'
    | '/diagnostics'
    | '/goals'
    | '/leaderboard'
    | '/api/slack-debug'
    | '/api/slack-followups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveBrandsRoute: typeof ActiveBrandsRoute
  AssetsRoute: typeof AssetsRoute
  BrandFinderRoute: typeof BrandFinderRoute
  CreatorsRoute: typeof CreatorsRoute
  DealsRoute: typeof DealsRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  GoalsRoute: typeof GoalsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiSlackDebugRoute: typeof ApiSlackDebugRoute
  ApiSlackFollowupsRoute: typeof ApiSlackFollowupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-finder': {
      id: '/brand-finder'
      path: '/brand-finder'
      fullPath: '/brand-finder'
      preLoaderRoute: typeof BrandFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-brands': {
      id: '/active-brands'
      path: '/active-brands'
      fullPath: '/active-brands'
      preLoaderRoute: typeof ActiveBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slack-followups': {
      id: '/api/slack-followups'
      path: '/api/slack-followups'
      fullPath: '/api/slack-followups'
      preLoaderRoute: typeof ApiSlackFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slack-debug': {
      id: '/api/slack-debug'
      path: '/api/slack-debug'
      fullPath: '/api/slack-debug'
      preLoaderRoute: typeof ApiSlackDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveBrandsRoute: ActiveBrandsRoute,
  AssetsRoute: AssetsRoute,
  BrandFinderRoute: BrandFinderRoute,
  CreatorsRoute: CreatorsRoute,
  DealsRoute: DealsRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  GoalsRoute: GoalsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiSlackDebugRoute: ApiSlackDebugRoute,
  ApiSlackFollowupsRoute: ApiSlackFollowupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
